# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2022-05-09 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cognitivenoise_group', to='otree.Session')),
            ],
            options={
                'db_table': 'cognitivenoise_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('treatment', otree.db.models.StringField(max_length=10000, null=True)),
                ('choice', otree.db.models.StringField(max_length=10000, null=True)),
                ('jsdectime_start', otree.db.models.FloatField(null=True)),
                ('jsdectime_end', otree.db.models.FloatField(null=True)),
                ('jsdectime', otree.db.models.FloatField(null=True)),
                ('pydectime', otree.db.models.FloatField(null=True)),
                ('pyresttime', otree.db.models.FloatField(null=True)),
                ('reward', otree.db.models.FloatField(null=True)),
                ('risk', otree.db.models.FloatField(null=True)),
                ('certainty', otree.db.models.FloatField(null=True)),
                ('display', otree.db.models.IntegerField(null=True)),
                ('lottery', otree.db.models.IntegerField(null=True)),
                ('decmode', otree.db.models.PositiveIntegerField(choices=[[7, 'Almost always (near 100% of the time)'], [6, 'Very often (about 80% of the time)'], [5, 'Moderately often (about 60% of the time)'], [4, 'About half of the time (50% of the time)'], [3, 'Moderately seldom (about 40% of the time)'], [2, 'Very seldom (about 20% of the time)'], [1, 'Almost never (near 0% of the time)']], null=True)),
                ('payoff_ddm', otree.db.models.LongStringField(null=True)),
                ('pay_pound', otree.db.models.FloatField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cognitivenoise.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cognitivenoise_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cognitivenoise_player', to='otree.Session')),
            ],
            options={
                'db_table': 'cognitivenoise_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cognitivenoise_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'cognitivenoise_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cognitivenoise.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cognitivenoise.Subsession'),
        ),
    ]
