# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2022-05-09 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='even_gamble_practice_group', to='otree.Session')),
            ],
            options={
                'db_table': 'even_gamble_practice_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('cq1_1', otree.db.models.PositiveIntegerField(choices=[[1, '40 points'], [2, '25 points']], null=True)),
                ('cq1_2', otree.db.models.PositiveIntegerField(choices=[[1, '40 points'], [2, '25 points']], null=True)),
                ('cq1_3', otree.db.models.PositiveIntegerField(choices=[[1, 'Winning: 25 percent; Losing: 75 percent'], [2, 'Winning: 40 percent; Losing: 60 percent'], [3, 'Winning: 50 percent; Losing: 50 percent']], null=True)),
                ('cq1_4', otree.db.models.PositiveIntegerField(choices=[[1, 'Pressing the Up Arrow key (↑)'], [2, 'Pressing the Down Arrow key (↓)']], null=True)),
                ('cq1_5', otree.db.models.PositiveIntegerField(choices=[[1, 'Pressing the Up Arrow key (↑)'], [2, 'Pressing the Down Arrow key (↓)']], null=True)),
                ('cq2_1', otree.db.models.PositiveIntegerField(choices=[[1, '100 points'], [2, '35 points'], [3, '70 points'], [4, 'None of the above']], null=True)),
                ('cq2_2', otree.db.models.PositiveIntegerField(choices=[[1, '170 points'], [2, '30 points'], [3, '135 points'], [4, '65 points']], null=True)),
                ('cq2_3', otree.db.models.PositiveIntegerField(choices=[[1, '170 points'], [2, '30 points'], [3, '135 points'], [4, '65 points']], null=True)),
                ('jsdectime_start', otree.db.models.FloatField(null=True)),
                ('jsdectime_end', otree.db.models.FloatField(null=True)),
                ('jsdectime', otree.db.models.FloatField(null=True)),
                ('pydectime', otree.db.models.FloatField(null=True)),
                ('pyresttime', otree.db.models.FloatField(null=True)),
                ('gain', otree.db.models.FloatField(null=True)),
                ('loss', otree.db.models.FloatField(null=True)),
                ('display', otree.db.models.IntegerField(null=True)),
                ('accept', otree.db.models.IntegerField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='even_gamble_practice.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='even_gamble_practice_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='even_gamble_practice_player', to='otree.Session')),
            ],
            options={
                'db_table': 'even_gamble_practice_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='even_gamble_practice_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'even_gamble_practice_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='even_gamble_practice.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='even_gamble_practice.Subsession'),
        ),
    ]
