# Generated by Django 2.2.12 on 2021-06-11 07:50

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('even_gamble_practice', '0002_auto_20210611_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='cq1_1',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '35 points'], [2, '75 points']], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='cq1_2',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '35 points'], [2, '75 points']], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='cq1_3',
            field=otree.db.models.PositiveIntegerField(choices=[[1, 'Wining: 35 percent; Losing: 65 percent'], [2, 'Wining: 75 percent; Losing: 25 percent'], [3, 'Wining: 50 percent; Losing: 50 percent']], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='cq1_4',
            field=otree.db.models.PositiveIntegerField(choices=[[1, 'Pressing the Up Arrow key (↑)'], [2, '$35'], [3, '$16'], [4, 'None of the above']], null=True),
        ),
    ]
