# Generated by Django 2.2.12 on 2021-06-11 08:30

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('even_gamble_practice', '0014_auto_20210611_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='cq1_4',
            field=otree.db.models.PositiveIntegerField(choices=[[1, 'Accept: Up Arrow key (↑); Reject: Down Arrow key (↓)'], [2, 'Accept: Down Arrow key (↓); Reject: Up Arrow key (↑)']], null=True),
        ),
    ]
