# Generated by Django 2.2.12 on 2021-06-11 10:25

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('even_gamble_practice', '0019_auto_20210611_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='cq2_1',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '100 points'], [2, '35 points'], [3, '70 points'], [4, 'None of the above']], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='cq2_2',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '170 points'], [2, '30 points'], [3, '135 points'], [4, '65']], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='cq2_3',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '170 points'], [2, '30 points'], [3, '135 points'], [4, '65']], null=True),
        ),
    ]
