# Generated by Django 2.2.12 on 2021-06-11 10:29

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('even_gamble_practice', '0020_auto_20210611_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='cq2_2',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '170 points'], [2, '30 points'], [3, '135 points'], [4, '65 points']], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='cq2_3',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '170 points'], [2, '30 points'], [3, '135 points'], [4, '65 points']], null=True),
        ),
    ]
