# Generated by Django 2.2.12 on 2021-04-11 22:19

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reitest_group', to='otree.Session')),
            ],
            options={
                'db_table': 'REItest_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reitest_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'REItest_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('prolific_code', otree.db.models.StringField(max_length=10000, null=True)),
                ('reflectiveness_score', otree.db.models.IntegerField(default=0, null=True)),
                ('intuitiveness_score', otree.db.models.IntegerField(default=0, null=True)),
                ('crt1', otree.db.models.StringField(max_length=10000, null=True)),
                ('crt2', otree.db.models.StringField(max_length=10000, null=True)),
                ('crt3', otree.db.models.StringField(max_length=10000, null=True)),
                ('crt4', otree.db.models.StringField(max_length=10000, null=True)),
                ('crt5', otree.db.models.StringField(max_length=10000, null=True)),
                ('crt6', otree.db.models.StringField(max_length=10000, null=True)),
                ('crt7', otree.db.models.StringField(max_length=10000, null=True)),
                ('bnt_score', otree.db.models.IntegerField(default=0, null=True)),
                ('bnt1', otree.db.models.StringField(max_length=10000, null=True)),
                ('bnt2', otree.db.models.StringField(max_length=10000, null=True)),
                ('bnt3', otree.db.models.StringField(max_length=10000, null=True)),
                ('bnt4', otree.db.models.StringField(max_length=10000, null=True)),
                ('nfcscore', otree.db.models.PositiveIntegerField(null=True)),
                ('fiscore', otree.db.models.PositiveIntegerField(null=True)),
                ('q1', otree.db.models.PositiveIntegerField(choices=[[1, '1 = definitely not true'], [2, '2 = somewhat not true'], [3, '3 = neither true nor untrue'], [4, '4 = somewhat true'], [5, '5 = definitely true']], null=True)),
                ('q2', otree.db.models.PositiveIntegerField(choices=[[1, '1 = definitely not true'], [2, '2 = somewhat not true'], [3, '3 = neither true nor untrue'], [4, '4 = somewhat true'], [5, '5 = definitely true']], null=True)),
                ('q3', otree.db.models.PositiveIntegerField(choices=[[1, '1 = definitely not true'], [2, '2 = somewhat not true'], [3, '3 = neither true nor untrue'], [4, '4 = somewhat true'], [5, '5 = definitely true']], null=True)),
                ('q4', otree.db.models.PositiveIntegerField(choices=[[1, '1 = definitely not true'], [2, '2 = somewhat not true'], [3, '3 = neither true nor untrue'], [4, '4 = somewhat true'], [5, '5 = definitely true']], null=True)),
                ('q5', otree.db.models.PositiveIntegerField(choices=[[1, '1 = definitely not true'], [2, '2 = somewhat not true'], [3, '3 = neither true nor untrue'], [4, '4 = somewhat true'], [5, '5 = definitely true']], null=True)),
                ('q6', otree.db.models.PositiveIntegerField(choices=[[1, '1 = definitely not true'], [2, '2 = somewhat not true'], [3, '3 = neither true nor untrue'], [4, '4 = somewhat true'], [5, '5 = definitely true']], null=True)),
                ('q7', otree.db.models.PositiveIntegerField(choices=[[1, '1 = definitely not true'], [2, '2 = somewhat not true'], [3, '3 = neither true nor untrue'], [4, '4 = somewhat true'], [5, '5 = definitely true']], null=True)),
                ('q8', otree.db.models.PositiveIntegerField(choices=[[1, '1 = definitely not true'], [2, '2 = somewhat not true'], [3, '3 = neither true nor untrue'], [4, '4 = somewhat true'], [5, '5 = definitely true']], null=True)),
                ('q9', otree.db.models.PositiveIntegerField(choices=[[1, '1 = definitely not true'], [2, '2 = somewhat not true'], [3, '3 = neither true nor untrue'], [4, '4 = somewhat true'], [5, '5 = definitely true']], null=True)),
                ('q10', otree.db.models.PositiveIntegerField(choices=[[1, '1 = definitely not true'], [2, '2 = somewhat not true'], [3, '3 = neither true nor untrue'], [4, '4 = somewhat true'], [5, '5 = definitely true']], null=True)),
                ('q11', otree.db.models.PositiveIntegerField(choices=[[1, '1 = definitely not true'], [2, '2 = somewhat not true'], [3, '3 = neither true nor untrue'], [4, '4 = somewhat true'], [5, '5 = definitely true']], null=True)),
                ('q12', otree.db.models.PositiveIntegerField(choices=[[1, '1 = definitely not true'], [2, '2 = somewhat not true'], [3, '3 = neither true nor untrue'], [4, '4 = somewhat true'], [5, '5 = definitely true']], null=True)),
                ('q13', otree.db.models.PositiveIntegerField(choices=[[1, '1 = definitely not true'], [2, '2 = somewhat not true'], [3, '3 = neither true nor untrue'], [4, '4 = somewhat true'], [5, '5 = definitely true']], null=True)),
                ('q14', otree.db.models.PositiveIntegerField(choices=[[1, '1 = definitely not true'], [2, '2 = somewhat not true'], [3, '3 = neither true nor untrue'], [4, '4 = somewhat true'], [5, '5 = definitely true']], null=True)),
                ('q15', otree.db.models.PositiveIntegerField(choices=[[1, '1 = definitely not true'], [2, '2 = somewhat not true'], [3, '3 = neither true nor untrue'], [4, '4 = somewhat true'], [5, '5 = definitely true']], null=True)),
                ('q16', otree.db.models.PositiveIntegerField(choices=[[1, '1 = definitely not true'], [2, '2 = somewhat not true'], [3, '3 = neither true nor untrue'], [4, '4 = somewhat true'], [5, '5 = definitely true']], null=True)),
                ('q17', otree.db.models.PositiveIntegerField(choices=[[1, '1 = definitely not true'], [2, '2 = somewhat not true'], [3, '3 = neither true nor untrue'], [4, '4 = somewhat true'], [5, '5 = definitely true']], null=True)),
                ('q18', otree.db.models.PositiveIntegerField(choices=[[1, '1 = definitely not true'], [2, '2 = somewhat not true'], [3, '3 = neither true nor untrue'], [4, '4 = somewhat true'], [5, '5 = definitely true']], null=True)),
                ('q19', otree.db.models.PositiveIntegerField(choices=[[1, '1 = definitely not true'], [2, '2 = somewhat not true'], [3, '3 = neither true nor untrue'], [4, '4 = somewhat true'], [5, '5 = definitely true']], null=True)),
                ('q20', otree.db.models.PositiveIntegerField(choices=[[1, '1 = definitely not true'], [2, '2 = somewhat not true'], [3, '3 = neither true nor untrue'], [4, '4 = somewhat true'], [5, '5 = definitely true']], null=True)),
                ('q21', otree.db.models.PositiveIntegerField(choices=[[1, '1 = definitely not true'], [2, '2 = somewhat not true'], [3, '3 = neither true nor untrue'], [4, '4 = somewhat true'], [5, '5 = definitely true']], null=True)),
                ('q22', otree.db.models.PositiveIntegerField(choices=[[1, '1 = definitely not true'], [2, '2 = somewhat not true'], [3, '3 = neither true nor untrue'], [4, '4 = somewhat true'], [5, '5 = definitely true']], null=True)),
                ('q23', otree.db.models.PositiveIntegerField(choices=[[1, '1 = definitely not true'], [2, '2 = somewhat not true'], [3, '3 = neither true nor untrue'], [4, '4 = somewhat true'], [5, '5 = definitely true']], null=True)),
                ('q24', otree.db.models.PositiveIntegerField(choices=[[1, '1 = definitely not true'], [2, '2 = somewhat not true'], [3, '3 = neither true nor untrue'], [4, '4 = somewhat true'], [5, '5 = definitely true']], null=True)),
                ('q25', otree.db.models.PositiveIntegerField(choices=[[1, '1 = definitely not true'], [2, '2 = somewhat not true'], [3, '3 = neither true nor untrue'], [4, '4 = somewhat true'], [5, '5 = definitely true']], null=True)),
                ('q26', otree.db.models.PositiveIntegerField(choices=[[1, '1 = definitely not true'], [2, '2 = somewhat not true'], [3, '3 = neither true nor untrue'], [4, '4 = somewhat true'], [5, '5 = definitely true']], null=True)),
                ('q27', otree.db.models.PositiveIntegerField(choices=[[1, '1 = definitely not true'], [2, '2 = somewhat not true'], [3, '3 = neither true nor untrue'], [4, '4 = somewhat true'], [5, '5 = definitely true']], null=True)),
                ('q28', otree.db.models.PositiveIntegerField(choices=[[1, '1 = definitely not true'], [2, '2 = somewhat not true'], [3, '3 = neither true nor untrue'], [4, '4 = somewhat true'], [5, '5 = definitely true']], null=True)),
                ('q29', otree.db.models.PositiveIntegerField(choices=[[1, '1 = definitely not true'], [2, '2 = somewhat not true'], [3, '3 = neither true nor untrue'], [4, '4 = somewhat true'], [5, '5 = definitely true']], null=True)),
                ('q30', otree.db.models.PositiveIntegerField(choices=[[1, '1 = definitely not true'], [2, '2 = somewhat not true'], [3, '3 = neither true nor untrue'], [4, '4 = somewhat true'], [5, '5 = definitely true']], null=True)),
                ('q31', otree.db.models.PositiveIntegerField(choices=[[1, '1 = definitely not true'], [2, '2 = somewhat not true'], [3, '3 = neither true nor untrue'], [4, '4 = somewhat true'], [5, '5 = definitely true']], null=True)),
                ('dt_start', otree.db.models.FloatField(null=True)),
                ('dt_end', otree.db.models.FloatField(null=True)),
                ('dt_crt1', otree.db.models.FloatField(null=True)),
                ('dt_crt2', otree.db.models.FloatField(null=True)),
                ('dt_crt3', otree.db.models.FloatField(null=True)),
                ('dt_crt4', otree.db.models.FloatField(null=True)),
                ('dt_crt5', otree.db.models.FloatField(null=True)),
                ('dt_crt6', otree.db.models.FloatField(null=True)),
                ('dt_crt7', otree.db.models.FloatField(null=True)),
                ('dt_bnt1', otree.db.models.FloatField(null=True)),
                ('dt_bnt2', otree.db.models.FloatField(null=True)),
                ('dt_bnt3', otree.db.models.FloatField(null=True)),
                ('dt_bnt4', otree.db.models.FloatField(null=True)),
                ('dt_rei', otree.db.models.FloatField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='REItest.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reitest_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reitest_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REItest.Subsession')),
            ],
            options={
                'db_table': 'REItest_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REItest.Subsession'),
        ),
    ]
