# Generated by Django 2.2.12 on 2021-06-14 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('even_gamble', '0002_auto_20210531_0434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='payoff_ddm',
        ),
    ]
