# Generated by Django 2.2.12 on 2021-06-14 04:02

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('even_gamble', '0003_remove_player_payoff_ddm'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='pay_info',
            field=otree.db.models.LongStringField(null=True),
        ),
    ]
