# Generated by Django 2.2.12 on 2021-07-10 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('even_gamble', '0005_auto_20210619_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='feedback_general',
        ),
        migrations.RemoveField(
            model_name='player',
            name='feedback_p1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='feedback_p2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='feedback_p3',
        ),
    ]
