# Generated by Django 2.2.12 on 2022-04-18 08:24

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('BDMauction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='BDM_order',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
