# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2022-05-09 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eci_survey_group', to='otree.Session')),
            ],
            options={
                'db_table': 'ECI_survey_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('prolific_code', otree.db.models.StringField(max_length=10000, null=True)),
                ('PA_score', otree.db.models.IntegerField(default=0, null=True)),
                ('NA_score', otree.db.models.IntegerField(default=0, null=True)),
                ('PA1', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Never'], [2, '2 = Rarely'], [3, '3 = Sometimes'], [4, '4 = Often'], [5, '5 = Always']], null=True)),
                ('PA2', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Never'], [2, '2 = Rarely'], [3, '3 = Sometimes'], [4, '4 = Often'], [5, '5 = Always']], null=True)),
                ('PA3', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Never'], [2, '2 = Rarely'], [3, '3 = Sometimes'], [4, '4 = Often'], [5, '5 = Always']], null=True)),
                ('PA4', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Never'], [2, '2 = Rarely'], [3, '3 = Sometimes'], [4, '4 = Often'], [5, '5 = Always']], null=True)),
                ('PA5', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Never'], [2, '2 = Rarely'], [3, '3 = Sometimes'], [4, '4 = Often'], [5, '5 = Always']], null=True)),
                ('NA1', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Never'], [2, '2 = Rarely'], [3, '3 = Sometimes'], [4, '4 = Often'], [5, '5 = Always']], null=True)),
                ('NA2', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Never'], [2, '2 = Rarely'], [3, '3 = Sometimes'], [4, '4 = Often'], [5, '5 = Always']], null=True)),
                ('NA3', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Never'], [2, '2 = Rarely'], [3, '3 = Sometimes'], [4, '4 = Often'], [5, '5 = Always']], null=True)),
                ('NA4', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Never'], [2, '2 = Rarely'], [3, '3 = Sometimes'], [4, '4 = Often'], [5, '5 = Always']], null=True)),
                ('NA5', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Never'], [2, '2 = Rarely'], [3, '3 = Sometimes'], [4, '4 = Often'], [5, '5 = Always']], null=True)),
                ('RTP_E', otree.db.models.IntegerField(default=0, null=True)),
                ('RTP_F', otree.db.models.IntegerField(default=0, null=True)),
                ('RTP_FI', otree.db.models.IntegerField(default=0, null=True)),
                ('RTP_FG', otree.db.models.IntegerField(default=0, null=True)),
                ('RTP_HS', otree.db.models.IntegerField(default=0, null=True)),
                ('RTP_R', otree.db.models.IntegerField(default=0, null=True)),
                ('RTP_S', otree.db.models.IntegerField(default=0, null=True)),
                ('RTP_average', otree.db.models.FloatField(default=0, null=True)),
                ('dq1', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True)),
                ('dq2', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True)),
                ('dq3', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True)),
                ('dq4', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True)),
                ('dq5', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True)),
                ('dq6', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True)),
                ('dq7', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True)),
                ('dq8', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True)),
                ('dq9', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True)),
                ('dq10', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True)),
                ('dq11', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True)),
                ('dq12', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True)),
                ('dq13', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True)),
                ('dq14', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True)),
                ('dq15', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True)),
                ('dq16', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True)),
                ('dq17', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True)),
                ('dq18', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True)),
                ('dq19', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True)),
                ('dq20', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True)),
                ('dq21', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True)),
                ('dq22', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True)),
                ('dq23', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True)),
                ('dq24', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True)),
                ('dq25', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True)),
                ('dq26', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True)),
                ('dq27', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True)),
                ('dq28', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True)),
                ('dq29', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True)),
                ('dq30', otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True)),
                ('reflectiveness_score', otree.db.models.IntegerField(default=0, null=True)),
                ('intuitiveness_score', otree.db.models.IntegerField(default=0, null=True)),
                ('crt1', otree.db.models.StringField(max_length=10000, null=True)),
                ('crt2', otree.db.models.StringField(max_length=10000, null=True)),
                ('crt3', otree.db.models.StringField(max_length=10000, null=True)),
                ('crt4', otree.db.models.StringField(max_length=10000, null=True)),
                ('crt5', otree.db.models.StringField(max_length=10000, null=True)),
                ('crt6', otree.db.models.StringField(max_length=10000, null=True)),
                ('crt7', otree.db.models.StringField(max_length=10000, null=True)),
                ('dt_start', otree.db.models.FloatField(null=True)),
                ('dt_end', otree.db.models.FloatField(null=True)),
                ('dt_dospert', otree.db.models.FloatField(null=True)),
                ('dt_panas', otree.db.models.FloatField(null=True)),
                ('dt_crt1', otree.db.models.FloatField(null=True)),
                ('dt_crt2', otree.db.models.FloatField(null=True)),
                ('dt_crt3', otree.db.models.FloatField(null=True)),
                ('dt_crt4', otree.db.models.FloatField(null=True)),
                ('dt_crt5', otree.db.models.FloatField(null=True)),
                ('dt_crt6', otree.db.models.FloatField(null=True)),
                ('dt_crt7', otree.db.models.FloatField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ECI_survey.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eci_survey_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eci_survey_player', to='otree.Session')),
            ],
            options={
                'db_table': 'ECI_survey_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eci_survey_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'ECI_survey_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ECI_survey.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ECI_survey.Subsession'),
        ),
    ]
