# Generated by Django 2.2.12 on 2021-04-14 17:22

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ECI_survey', '0002_auto_20210414_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='NA1',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Never'], [2, '2 = Rarely'], [3, '3 = Sometimes'], [4, '4 = Often'], [5, '5 = Always']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='NA2',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Never'], [2, '2 = Rarely'], [3, '3 = Sometimes'], [4, '4 = Often'], [5, '5 = Always']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='NA3',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Never'], [2, '2 = Rarely'], [3, '3 = Sometimes'], [4, '4 = Often'], [5, '5 = Always']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='NA4',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Never'], [2, '2 = Rarely'], [3, '3 = Sometimes'], [4, '4 = Often'], [5, '5 = Always']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='NA5',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Never'], [2, '2 = Rarely'], [3, '3 = Sometimes'], [4, '4 = Often'], [5, '5 = Always']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='NA_score',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='PA1',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Never'], [2, '2 = Rarely'], [3, '3 = Sometimes'], [4, '4 = Often'], [5, '5 = Always']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='PA2',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Never'], [2, '2 = Rarely'], [3, '3 = Sometimes'], [4, '4 = Often'], [5, '5 = Always']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='PA3',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Never'], [2, '2 = Rarely'], [3, '3 = Sometimes'], [4, '4 = Often'], [5, '5 = Always']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='PA4',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Never'], [2, '2 = Rarely'], [3, '3 = Sometimes'], [4, '4 = Often'], [5, '5 = Always']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='PA5',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Never'], [2, '2 = Rarely'], [3, '3 = Sometimes'], [4, '4 = Often'], [5, '5 = Always']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='PA_score',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dt_panas',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
