# Generated by Django 2.2.12 on 2021-07-10 00:01

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ECI_survey', '0003_auto_20210414_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='prolific_code',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
