# Generated by Django 2.2.12 on 2021-08-01 19:48

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ECI_survey', '0005_auto_20210801_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='MU1',
            field=otree.db.models.IntegerField(choices=[[1, 'Yes (at least one dose)'], [0, 'No']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='MUF_score',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
    ]
