# Generated by Django 2.2.12 on 2021-08-13 19:47

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ECI_survey', '0007_auto_20210801_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='RM_cosmetic',
            field=otree.db.models.IntegerField(choices=[[1, '1 = Very Unlikely'], [2, '2'], [3, '3'], [4, '4 = Neutral'], [5, '5'], [6, '6'], [7, '7 = Very Likely']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='RM_cosmeticscore',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='RM_fail',
            field=otree.db.models.IntegerField(choices=[[1, '1 = Very Unlikely'], [2, '2'], [3, '3'], [4, '4 = Neutral'], [5, '5'], [6, '6'], [7, '7 = Very Likely']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='RM_funcscore',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='RM_likelytobuy',
            field=otree.db.models.IntegerField(choices=[[1, '1 = Very Unlikely'], [2, '2'], [3, '3'], [4, '4 = Neutral'], [5, '5'], [6, '6'], [7, '7 = Very Likely']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='RM_problems',
            field=otree.db.models.IntegerField(choices=[[1, '1 = Very Unlikely'], [2, '2'], [3, '3'], [4, '4 = Neutral'], [5, '5'], [6, '6'], [7, '7 = Very Likely']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='RM_reliable',
            field=otree.db.models.IntegerField(choices=[[1, '1 = Very Unlikely'], [2, '2'], [3, '3'], [4, '4 = Neutral'], [5, '5'], [6, '6'], [7, '7 = Very Likely']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='RM_returned',
            field=otree.db.models.IntegerField(choices=[[1, '1 = Very Unlikely'], [2, '2'], [3, '3'], [4, '4 = Neutral'], [5, '5'], [6, '6'], [7, '7 = Very Likely']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='RM_scratches',
            field=otree.db.models.IntegerField(choices=[[1, '1 = Very Unlikely'], [2, '2'], [3, '3'], [4, '4 = Neutral'], [5, '5'], [6, '6'], [7, '7 = Very Likely']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='RM_worn',
            field=otree.db.models.IntegerField(choices=[[1, '1 = Very Unlikely'], [2, '2'], [3, '3'], [4, '4 = Neutral'], [5, '5'], [6, '6'], [7, '7 = Very Likely']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='WTP_iPhone',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='MU2',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Very Unlikely'], [2, '2'], [3, '3'], [4, '4 = Neutral'], [5, '5'], [6, '6'], [7, '7 = Very Likely']], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='MU3',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Very Unlikely'], [2, '2'], [3, '3'], [4, '4 = Neutral'], [5, '5'], [6, '6'], [7, '7 = Very Likely']], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='MU4',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Very Unlikely'], [2, '2'], [3, '3'], [4, '4 = Neutral'], [5, '5'], [6, '6'], [7, '7 = Very Likely']], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='MU5',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Very Unlikely'], [2, '2'], [3, '3'], [4, '4 = Neutral'], [5, '5'], [6, '6'], [7, '7 = Very Likely']], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='MU6',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Very Unlikely'], [2, '2'], [3, '3'], [4, '4 = Neutral'], [5, '5'], [6, '6'], [7, '7 = Very Likely']], null=True),
        ),
    ]
