# Generated by Django 2.2.12 on 2021-08-20 02:22

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ECI_survey', '0008_auto_20210813_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='MU1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='MU2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='MU3',
        ),
        migrations.RemoveField(
            model_name='player',
            name='MU4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='MU5',
        ),
        migrations.RemoveField(
            model_name='player',
            name='MU6',
        ),
        migrations.RemoveField(
            model_name='player',
            name='MUF_score',
        ),
        migrations.RemoveField(
            model_name='player',
            name='RM_cosmetic',
        ),
        migrations.RemoveField(
            model_name='player',
            name='RM_cosmeticscore',
        ),
        migrations.RemoveField(
            model_name='player',
            name='RM_fail',
        ),
        migrations.RemoveField(
            model_name='player',
            name='RM_funcscore',
        ),
        migrations.RemoveField(
            model_name='player',
            name='RM_likelytobuy',
        ),
        migrations.RemoveField(
            model_name='player',
            name='RM_problems',
        ),
        migrations.RemoveField(
            model_name='player',
            name='RM_reliable',
        ),
        migrations.RemoveField(
            model_name='player',
            name='RM_returned',
        ),
        migrations.RemoveField(
            model_name='player',
            name='RM_scratches',
        ),
        migrations.RemoveField(
            model_name='player',
            name='RM_worn',
        ),
        migrations.RemoveField(
            model_name='player',
            name='WTP_iPhone',
        ),
        migrations.RemoveField(
            model_name='player',
            name='dt_mask',
        ),
        migrations.RemoveField(
            model_name='player',
            name='dt_remanufac',
        ),
        migrations.AddField(
            model_name='player',
            name='dt_dospert',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
