# Generated by Django 2.2.12 on 2021-08-20 03:42

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ECI_survey', '0010_auto_20210820_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='dq1',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True),
        ),
    ]
