# Generated by Django 2.2.12 on 2021-08-20 04:57

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ECI_survey', '0011_player_dq1'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='dq10',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dq11',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dq12',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dq13',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dq14',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dq15',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dq16',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dq17',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dq18',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dq19',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dq2',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dq20',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dq21',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dq22',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dq23',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dq24',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dq25',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dq26',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dq27',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dq28',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dq29',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dq3',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dq30',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dq4',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dq5',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dq6',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dq7',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dq8',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dq9',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = Extremely Unlikely'], [2, '2 = Moderately Unlikely'], [3, '3 = Somewhat Unlikely'], [4, '4 = Not Sure'], [5, '5 = Somewhat Likely'], [6, '6 = Moderately Likely'], [7, '7 = Extremely Likely']], null=True),
        ),
    ]
