# Generated by Django 2.2.12 on 2021-08-20 05:04

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ECI_survey', '0012_auto_20210820_0557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='score_E',
        ),
        migrations.RemoveField(
            model_name='player',
            name='score_F',
        ),
        migrations.RemoveField(
            model_name='player',
            name='score_HS',
        ),
        migrations.RemoveField(
            model_name='player',
            name='score_R',
        ),
        migrations.RemoveField(
            model_name='player',
            name='score_S',
        ),
        migrations.RemoveField(
            model_name='player',
            name='score_average',
        ),
        migrations.AddField(
            model_name='player',
            name='RTP_E',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='RTP_F',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='RTP_HS',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='RTP_R',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='RTP_S',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='RTP_average',
            field=otree.db.models.FloatField(default=0, null=True),
        ),
    ]
