# Generated by Django 2.2.12 on 2021-08-20 05:19

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ECI_survey', '0013_auto_20210820_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='RTP_FG',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='RTP_FI',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
    ]
